- name: declsre variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: acess a variable
      ansible.builtin.debug:
        msg: URL == {{URL}


- name: access a variable in anoter file
  hosts: all
  connection: local
  vars_file:
      - var.yml
  tasks:
   - name: declare and access a variable
     ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare variable at task level
  hosts: all
  connection: local
  tasks:
    - name: declare and access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task123.example.com